# FastAPI
server:
  cors_origins: ["*"]
  max_message_length: 1024
  cors_max_age: 3600

# RAG
db:
  collection_name: "FAQ"

embedder:
  type: "sentence_transformer"
  repo: "BAAI/bge-m3" # used if type is "sentence_transformer"

retriever:
  top_k: 3
  score_threshold: 0.5

reranker:
  apply: False
  type: "sentence_transformer"
  repo: "jinaai/jina-reranker-v2-base-multilingual" # used if type is "sentence_transformer"
  top_k: 3
  score_threshold: 0.5